json_vars = {'tweet_vars': {'userId': '', 'count': 6, 'includePromotedContent': True,
                            'withQuickPromoteEligibilityTweetFields': True, 'withSuperFollowsUserFields': True,
                            'withDownvotePerspective': False, 'withReactionsMetadata': False,
                            'withReactionsPerspective': False,
                            'withSuperFollowsTweetFields': True, 'withVoice': True, 'withV2Timeline': True},
             'reply_vars': {'focalTweetId': '', 'with_rux_injections': False, 'count': 50,
                            'includePromotedContent': True, 'withCommunity': True,
                            'withQuickPromoteEligibilityTweetFields': True, 'withBirdwatchNotes': True,
                            'withSuperFollowsUserFields': True, 'withDownvotePerspective': False,
                            'withReactionsMetadata': False, 'withReactionsPerspective': False,
                            'withSuperFollowsTweetFields': True, 'withVoice': True, 'withV2Timeline': True},
             'features_reply': {'responsive_web_twitter_blue_verified_badge_is_enabled': True,
                                'responsive_web_graphql_exclude_directive_enabled': True,
                                'verified_phone_label_enabled': False,
                                'responsive_web_graphql_timeline_navigation_enabled': True,
                                'responsive_web_graphql_skip_user_profile_image_extensions_enabled': False,
                                'tweetypie_unmention_optimization_enabled': True, 'vibe_api_enabled': True,
                                'responsive_web_edit_tweet_api_enabled': True,
                                'graphql_is_translatable_rweb_tweet_is_translatable_enabled': True,
                                'view_counts_everywhere_api_enabled': True,
                                'longform_notetweets_consumption_enabled': True,
                                'tweet_awards_web_tipping_enabled': False,
                                'freedom_of_speech_not_reach_fetch_enabled': False,
                                'standardized_nudges_misinfo': True,
                                'tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled': False,
                                'interactive_text_enabled': True, 'responsive_web_text_conversations_enabled': False,
                                'longform_notetweets_richtext_consumption_enabled': False,
                                'responsive_web_enhance_cards_enabled': False},

             'features_tweet': {'responsive_web_twitter_blue_verified_badge_is_enabled': True,
                                'responsive_web_graphql_exclude_directive_enabled': True,
                                'verified_phone_label_enabled': False,
                                'responsive_web_graphql_timeline_navigation_enabled': True,
                                'responsive_web_graphql_skip_user_profile_image_extensions_enabled': False,
                                'tweetypie_unmention_optimization_enabled': True, 'vibe_api_enabled': True,
                                'responsive_web_edit_tweet_api_enabled': True,
                                'graphql_is_translatable_rweb_tweet_is_translatable_enabled': True,
                                'view_counts_everywhere_api_enabled': True,
                                'longform_notetweets_consumption_enabled': True,
                                'tweet_awards_web_tipping_enabled': False,
                                'freedom_of_speech_not_reach_fetch_enabled': False,
                                'standardized_nudges_misinfo': True,
                                'tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled': False,
                                'interactive_text_enabled': True, 'responsive_web_text_conversations_enabled': False,
                                'longform_notetweets_richtext_consumption_enabled': False,
                                'responsive_web_enhance_cards_enabled': False}}
